version: "3.7"
networks:
  npm_proxy_network:
services:
  # https://docs.linuxserver.io/images/docker-plex
  plex:
    image: linuxserver/plex:latest
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
      PLEX_CLAIM: "${PLEX_CLAIM}"
    networks:
      - npm_proxy_network
    volumes:
      - "${CONFIG_DIR}/plex:/config"
      - "${MEDIA_DIR}:/media"
    tmpfs:
      - "/tmp"
  # https://docs.linuxserver.io/images/docker-jellyfin
  jellyfin:
    image: linuxserver/jellyfin:latest
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
      JELLYFIN_PublishedServerUrl: "${JELLYFIN_HOST}"
    networks:
      - npm_proxy_network
    volumes:
      - "${CONFIG_DIR}/jellyfin:/config"
      - "${MEDIA_DIR}:/media"
  # https://hub.docker.com/r/linuxserver/prowlarr
  prowlarr:
    image: linuxserver/prowlarr:0.2.0-develop
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - npm_proxy_network
    volumes:
      - "${CONFIG_DIR}/prowlarr:/config"
  # https://docs.linuxserver.io/images/docker-nzbget
  nzbget:
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - npm_proxy_network
    volumes:
      - "${CONFIG_DIR}/nzbget:/config"
      - "${DOWNLOADS_DIR}:/downloads"
  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - npm_proxy_network
    volumes:
      - "${CONFIG_DIR}/sonarr:/config"
      - "${DOWNLOADS_DIR}:/downloads"
      - "${MEDIA_DIR}:/media"
    links:
      - nzbhydra
      - nzbget
      - transmission
  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - npm_proxy_network
    volumes:
      - "${CONFIG_DIR}/radarr:/config"
      - "${DOWNLOADS_DIR}:/downloads"
      - "${MEDIA_DIR}:/media"
    links:
      - nzbhydra
      - nzbget
      - transmission
  # https://docs.linuxserver.io/images/docker-nzbhydra
  nzbhydra:
    image: linuxserver/nzbhydra2:latest
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - npm_proxy_network
    volumes:
      - "${CONFIG_DIR}/nzbhydra:/config"
      - "${DOWNLOADS_DIR}:/downloads"
  # https://docs.linuxserver.io/images/docker-duplicati
  duplicati:
    image: linuxserver/duplicati:latest
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/duplicati:/config:rw
      - ./:/source:rw
      - ${BACKUP_DIR}:/backupdir:rw
      - ${CONFIG_DIR}:/allconf:ro
    networks:
      - npm_proxy_network
  # https://hub.docker.com/r/netdata/netdata
  netdata:
    image: netdata/netdata:latest
    restart: unless-stopped
    hostname: ${NETDATA_HOST}
    environment:
      PGID: ${DOCKER_PGID}
      TZ: ${TZ}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - npm_proxy_network
  # https://hub.docker.com/r/linuxserver/transmission    
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - ${CONFIG_DIR}/transmission:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${DOWNLOADS_DIR}/jackett:/watch
    networks:
      - npm_proxy_network
  # https://hub.docker.com/r/linuxserver/bazarr
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - "${CONFIG_DIR}/bazarr:/config"
      - "${MEDIA_DIR}/Movies:/movies"
      - "${MEDIA_DIR}/TV:/tv"
      - "${MEDIA_DIR}/Series:/series"
    networks:
      - npm_proxy_network
  # https://hub.docker.com/r/linuxserver/lidarr
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - "${CONFIG_DIR}/lidarr:/config"
      - "${MEDIA_DIR}/Music:/music"
      - "${DOWNLOADS_DIR}:/downloads"
    networks:
      - npm_proxy_network
  # https://hub.docker.com/r/jc21/nginx-proxy-manager
  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - "${CONFIG_DIR}/npm:/data"
      - "${CONFIG_DIR}/npm/letsencrypt:/etc/letsencrypt"
    networks:
      - npm_proxy_network
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
  # https://hub.docker.com/r/deluan/navidrome
  navidrome:
    image: deluan/navidrome:latest
    restart: unless-stopped
    user: ${PUID}:${PGID}
    environment:
      TZ: ${TZ}
      ND_SCANSCHEDULE: "@every 1m"
      ND_LOGLEVEL: debug  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "${CONFIG_DIR}/navidrome:/data"
      - "${MEDIA_DIR}/Music:/music:ro"
    networks:
      - npm_proxy_network
  # https://hub.docker.com/r/b4bz/homer
  homer:
    image: b4bz/homer:latest
    restart: unless-stopped
    volumes:
      - "${CONFIG_DIR}/homer/assets/:/www/assets"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - npm_proxy_network
  # https://hub.docker.com/r/sctx/overseerr
  overseerr:
    image: sctx/overseerr:latest
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      LOG_LEVEL: debug
    volumes:
      - "${CONFIG_DIR}/overseerr:/app/config"
    networks:
      - npm_proxy_network