version: "3.7"
networks:
  npm_proxy_network:
services:
  # https://docs.linuxserver.io/images/docker-plex
  plex:
    image: linuxserver/plex:latest
    restart: unless-stopped
    container_name: plex
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
      PLEX_CLAIM: "${PLEX_CLAIM}"
    networks:
      - npm_proxy_network
    volumes:
      - "${CONFIG_DIR}/plex:/config"
      - "${MEDIA_DIR}:/media"
    tmpfs:
      - "/tmp"
  # https://docs.linuxserver.io/images/docker-jellyfin
  jellyfin:
    image: linuxserver/jellyfin:latest
    restart: unless-stopped
    container_name: jellyfin
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
      JELLYFIN_PublishedServerUrl: "${JELLYFIN_HOST}"
    networks:
      - npm_proxy_network
    volumes:
      - "${CONFIG_DIR}/jellyfin:/config"
      - "${MEDIA_DIR}:/media"
  # https://hub.docker.com/r/sctx/overseerr
  overseerr:
    image: sctx/overseerr:latest
    restart: unless-stopped
    container_name: overseerr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      LOG_LEVEL: debug
    volumes:
      - "${CONFIG_DIR}/overseerr:/app/config"
    networks:
      - npm_proxy_network
  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    container_name: sonarr
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - npm_proxy_network
    volumes:
      - "${CONFIG_DIR}/sonarr:/config"
      - "${DOWNLOADS_DIR}:/downloads"
      - "${MEDIA_DIR}:/media"
    # links:
    #   - nzbhydra
    #   - nzbget
    #   - qbittorrent
  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    container_name: radarr
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - npm_proxy_network
    volumes:
      - "${CONFIG_DIR}/radarr:/config"
      - "${DOWNLOADS_DIR}:/downloads"
      - "${MEDIA_DIR}:/media"
    # links:
    #   - nzbhydra
    #   - nzbget
    #   - qbittorrent
  # https://hub.docker.com/r/linuxserver/bazarr
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    container_name: bazarr
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - "${CONFIG_DIR}/bazarr:/config"
      - "${MEDIA_DIR}/Movies:/movies"
      - "${MEDIA_DIR}/TV:/tv"
      - "${MEDIA_DIR}/Series:/series"
    networks:
      - npm_proxy_network
  # https://hub.docker.com/r/linuxserver/lidarr
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    container_name: lidarr
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - "${CONFIG_DIR}/lidarr:/config"
      - "${MEDIA_DIR}/Music:/music"
      - "${DOWNLOADS_DIR}:/downloads"
    networks:
      - npm_proxy_network
    # links:
    #   - nzbhydra
    #   - nzbget
    #   - qbittorrent
  # https://hub.docker.com/r/linuxserver/prowlarr
  prowlarr:
    image: linuxserver/prowlarr:0.2.0-develop
    restart: unless-stopped
    container_name: prowlarr
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - npm_proxy_network
    volumes:
      - "${CONFIG_DIR}/prowlarr:/config"
  # https://hub.docker.com/r/linuxserver/qbittorrent
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    container_name: qbittorrent
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
      WEBUI_PORT: "8080"
    networks:
      - npm_proxy_network
    volumes:
      - "${CONFIG_DIR}/qbittorent:/config"
      - "${DOWNLOADS_DIR}:/downloads"
  # https://hub.docker.com/r/jlesage/jdownloader-2
  jdownloader-2:
    image: jlesage/jdownloader-2
    restart: unless-stopped
    container_name: jdownloader-2
    environment:
      GROUP_ID: "${PGID}"
      USER_ID: "${PUID}"
      TZ: "${TZ}"
    networks:
      - npm_proxy_network
    ports:
      - "5800:5800"
    volumes:
      - "${CONFIG_DIR}/jdownloader-2:/config:rw"
      - "${DOWNLOADS_DIR}/jd2:/output:rw"
  # https://docs.linuxserver.io/images/docker-nzbget
  nzbget:
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    container_name: nzbget
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - npm_proxy_network
    volumes:
      - "${CONFIG_DIR}/nzbget:/config"
      - "${DOWNLOADS_DIR}:/downloads"
  # https://docs.linuxserver.io/images/docker-nzbhydra
  nzbhydra:
    image: linuxserver/nzbhydra2:latest
    restart: unless-stopped
    container_name: nzbhydra
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - npm_proxy_network
    volumes:
      - "${CONFIG_DIR}/nzbhydra:/config"
      - "${DOWNLOADS_DIR}:/downloads"
  # https://github.com/ajnart/homarr/pkgs/container/homarr    
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    container_name: homarr
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - npm_proxy_network
    volumes:
      - "${CONFIG_DIR}/homarr/configs:/app/data/configs"
      - "${CONFIG_DIR}/homarr/public/icons:/app/public/icons"
  # https://hub.docker.com/r/deluan/navidrome
  navidrome:
    image: deluan/navidrome:latest
    restart: unless-stopped
    user: ${PUID}:${PGID}
    container_name: navidrome
    environment:
      TZ: ${TZ}
      ND_SCANSCHEDULE: "@every 1m"
      ND_LOGLEVEL: debug  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "${CONFIG_DIR}/navidrome:/data"
      - "${MEDIA_DIR}/Music:/music:ro"
    networks:
      - npm_proxy_network
  # https://hub.docker.com/r/linuxserver/tautulli
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    restart: unless-stopped
    container_name: tautulli
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - "${CONFIG_DIR}/tautulli:/config:rw"
    networks:
      - npm_proxy_network
  # https://hub.docker.com/r/netdata/netdata
  netdata:
    image: netdata/netdata:latest
    restart: unless-stopped
    hostname: ${NETDATA_HOST}
    container_name: netdata
    environment:
      PGID: ${DOCKER_PGID}
      TZ: ${TZ}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - npm_proxy_network
  # https://hub.docker.com/r/jc21/nginx-proxy-manager
  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    container_name: npm
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - "${CONFIG_DIR}/npm:/data"
      - "${CONFIG_DIR}/npm/letsencrypt:/etc/letsencrypt"
    networks:
      - npm_proxy_network
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
  # https://hub.docker.com/r/filebrowser/filebrowser
  filebrowser:
    restart: unless-stopped
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - "${MEDIA_DIR}:/mediastack:rw"
      - "${CONFIG_DIR}/filebrowser/settings.json:/config/settings.json"
    networks:
      - npm_proxy_network
  # https://docs.linuxserver.io/images/docker-duplicati
  duplicati:
    image: linuxserver/duplicati:latest
    restart: unless-stopped
    container_name: duplicati
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_DIR}/duplicati:/config:rw
      - ./:/source:rw
      - ${BACKUP_DIR}:/backupdir:rw
      - ${CONFIG_DIR}:/allconf:ro
    networks:
      - npm_proxy_network
  
